### ISSUE TITLE
Package name in bsconfig.json and package.json don't match

### ISSUE THREAD

**Issue by dratini0** [state-machine-systems/JsonCodec#16]
The package name listed in `bsconfig.json` is `bs-json-codec`, while in `package.json` it is listed as `json-codec`. This causes issues with both webpack and require.js. Would it be possible to change either of them to match the other?

**Comment by johnwright** [comment]
Thanks, I missed this when changing the name to `json-codec` across the board.

**Comment by dratini0** [comment]
Thank you for this fix. I have updated my project, and it seems to have helped.

**Comment by johnwright** [comment]
Good to hear it! Let me know if you run into any other issues.
